### ISSUE TITLE
Calling From Within Another Plugin: Origin of Source Map

### ISSUE THREAD

**Issue by stahlbauer** [kwonoj/swc-plugin-coverage-instrument#182]
Given the current SWC plugin infrastructure, a plugin is initialized with the following method:

```
#[plugin_transform]
pub fn process_transform(
    mut program: Program,
    metadata: TransformPluginProgramMetadata,
) -> Program {
 ...
```
From within that method, I would like to call the instrumenter plugin with all relevant attributes of  `InstrumenterOptions`. Where do I get the `input_source_map` of type `istanbul-oxide/source_map::SourceMap` from? The object `metadata.source_map` is of type `PluginSourceMapProxy` and does not provide access to all information of the underlying sourcemap. 

Thanks for this work/software.

**Comment by kwonoj** [comment]
`istanbul-oxide/source_map::SourceMap` is not `metadata.source_map`. As you figured, `input_source_map` is an option value coming through `InstrumenterOptions` - which _user_ need to provide via swc's plugin config. Visitor, or your plugin should accept it in the same manner and pass it, it is neither autogenerated nor inferred inside by the plugin.

**Comment by stahlbauer** [comment]
I would be looking for an approach that is more in the line with the approach taken by the `babel-plugin-istanbul`---see the [Babel Plugin Istanbul Page](https://github.com/istanbuljs/babel-plugin-istanbul). For example, when using the plugin programatically, it allows
```
import babelPluginIstanbul from 'babel-plugin-istanbul';

function instrument(sourceCode, sourceMap, fileName) {
  return babel.transform(sourceCode, {
    filename,
    plugins: [
      [babelPluginIstanbul, {
        inputSourceMap: sourceMap
      }]
    ]
  })
}
```

The concrete problem I am currently facing is that the attribute `inputSourceMap` currently does not seem to be filled if not passing the sourcemap in `InstrumenterOptions`.

**Comment by stahlbauer** [comment]
Regarding `or your plugin should accept it in the same manner and pass it`:
I will try this. Thanks. (But it might lack information from intermediate transformation steps, for example, conducted by a transformation `chain`??)

**Comment by stahlbauer** [comment]
> your plugin should accept it in the same manner and pass it

For my specific use case, this is currently sufficient (I hope so) and works. Thanks.
