### ISSUE TITLE
Not working with Cypress, webpack, swc-loader and @swc/core 1.3.39 and 1.3.40

### ISSUE THREAD

**Issue by MattyBalaam** [kwonoj/swc-plugin-coverage-instrument#200]
We have attempted to upgrade from @swc/core from 1.3.38 to 1.3.39 and 1.3.40 but are now getting some compilation errors. If I remove the plugin from `experimental.plugins` then it runs

<img width="569" alt="Screenshot 2023-03-14 at 13 32 26" src="https://user-images.githubusercontent.com/1246923/225016979-5f204c2d-5665-4507-b884-3b83f2db6ef2.png">

**Comment by MattyBalaam** [comment]
As a side-note I’ve attempted to run the tests in this repo. But it’s my first time running Rust and I’m not sure what I am doing. I kept getting missing package errors and followed instructions to add them as it happened, but am a bit stuck here:
 
<img width="1424" alt="Screenshot 2023-03-14 at 13 57 08" src="https://user-images.githubusercontent.com/1246923/225024144-680ae488-a33a-4043-85be-ba110631705b.png">

**Comment by MattyBalaam** [comment]
This now has an issue in swc: https://github.com/swc-project/swc/issues/7238

**Comment by MattyBalaam** [comment]
@kwonoj thank you for trying to track down this issue.

 I have updated to `@swc/core 1.3.55` and `swc-plugin-coverage-instrumet 0.0.17`but I am still seeing the error on my M1 Mac. It happenes in Cypress and also Jest tests.
 
Would it be helpful for me to create a test repo?

**Comment by kwonoj** [comment]
Looks like this issue have multiple things, the one fixed is https://github.com/swc-project/swc/issues/7238. For the original one https://github.com/kwonoj/swc-plugin-coverage-instrument/issues/200#issue-1623491262, I don't have an idea how plugin would affect those, since your screenshot points `(): any =>` which is preserving typescript syntax, cause of ther error.

Plugin does not have way to control those. You'll probably need to investigate elsewhere.

**Comment by MattyBalaam** [comment]
My apologies, I have re-looked at the original issue I posted. At some point over the last month when I have tried various sec updates the error changed to one about memory access and I had forgotten there was a different error message in my original post:

I see lots of messages like this now, I assume this is covered by other open issues?

```
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/matthewbalaam/xxxxxx.cy.tsx")'

Caused by:
    0: failed to invoke `swc-plugin-coverage-instrument` as js transform plugin at ../../../node_modules/swc-plugin-coverage-instrument/target/wasm32-wasi/release/swc_plugin_coverage.wasm
    1: RuntimeError: out of bounds memory access
    2: heap_get_oob', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.260.35/src/plugin.rs:219:14
```

**Comment by MattyBalaam** [comment]
Hmm, I’ve just tried a combination of @swc/core `1.3.39` or `1.3.40` and `0.0.15` to trace back the issue and the tests run fine for me with that combination, but not if I then bump to `0.0.17`.

I get similar errors with` 1.3.55` and `0.0.15` though. I’m not exactly sure which version starts breaking, but with `1.3.45`  the terminal just gets to a point where it stalls before running tests.

Hope this is helpful in some way.

**Comment by MattyBalaam** [comment]
With the latest v0.0.18 release the plugin now seems to work with a wide range of swc releases, including the latest.
