### ISSUE TITLE
use client directive must be placed before other expressions

### ISSUE THREAD

**Issue by hect1c** [kwonoj/swc-plugin-coverage-instrument#214]
Using latest next `13.4.1-canary.0` and latest swc-plugin-coverage-instrument `0.0.18` and when running `next dev` get the following error

```
The "use client" directive must be placed before other expressions. Move it to the top of the file to resolve this issue.

   ,-[/nextjs-app-repro/node_modules/.pnpm/next@13.4.1-canary.0_@babel+core@7.20.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/script.js:1:1]
 1 | "use client";
   : ^^^^^^^^^^^^^
 2 | "use strict";
 3 | Object.defineProperty(exports, "__esModule", {
 4 |     value: true
   `----

The error was caused by importing 'next/dist/client/next-dev.js' in 'undefined'.
```

Here is a minimal repro https://github.com/hect1c/nextjs-app-repro install dependencies and run dev. When I remove the swc plugin it runs fine but when I add it then the issue appears. 

Oddly enough this happens in another project using same latest version but I don't use the App directory and am using pages and thus not utilizing any of the RSC features.

**Comment by kwonoj** [comment]
Plugin _may_ able to do this by their own, but in my opinion this should be handled in upstream swc itself.

https://github.com/swc-project/swc/issues/7315

**Comment by jpierson-at-riis** [comment]
We are still seeing this issue, or it's potentially cropped up again with current version of Next.JS. Our team is just getting familiar with Next.js as we are migrating some projects from CRA and have run into this issue while getting our coverage setup working with CypressJS. 

swc-plugin-coverage-instrument version: `0.0.24`
Next.js Version: `14.2.7`
Cypress.js: `13.13.3`
