### ISSUE TITLE
Latest Plugin incompatible with Next.JS 13.4.4.

### ISSUE THREAD

**Issue by fritterhoff** [kwonoj/swc-plugin-coverage-instrument#216]
Hey!

I'm currently struggeling, to get the this plugin working with Next.JS 13.4.4 From my point of view this will maybe be caused by different swc versions as mentioned in other issues before? Can somebody maybe provide me a working configuration?

**Comment by michaelhays** [comment]
See #214. We're waiting on this to be fixed upstream in swc.

**Comment by fritterhoff** [comment]
Okay. Actually I forgot to add the logs. Sadly I get an other error:
```
./pages/_app.tsx
Error: Filesystem cache is not enabled, cannot read plugin from phsyical path

./pages/_document.tsx
Error: Filesystem cache is not enabled, cannot read plugin from phsyical path

./pages/_error.tsx
Error: Filesystem cache is not enabled, cannot read plugin from phsyical path

./pages/auth/error.tsx
Error: Filesystem cache is not enabled, cannot read plugin from phsyical path

./pages/auth/signin.tsx
Error: Filesystem cache is not enabled, cannot read plugin from phsyical path
```

I can try to setup a small repo that allows reproducing this error.

**Comment by kwonoj** [comment]
That error message comes from upstream next.js with next-swc, not cause of the plugin.

**Comment by fritterhoff** [comment]
Well it only occurs if I enable the plugin. Without the plugin building my web app works fine.

**Comment by kwonoj** [comment]
Cause error is about loading plugin in next.js.
