### ISSUE TITLE
failed to invoke `xxx.wasm` as js transform plugin, RuntimeError: call stack exhausted

### ISSUE THREAD

**Issue by Mistrain-y-y** [kwonoj/swc-plugin-coverage-instrument#218]
i tried to use this swc plugin, but i got this error.

next version 13.1.1
swc-plugin-coverage-instrument version 0.0.18

```ts
experimental: {
        swcPlugins: [
            [
                'swc-plugin-coverage-instrument', {
                    coverageVariable: 'xxx-coverage',
                    include: ['components/**']
                }
            ]
        ],
    }
```

error - ./node_modules/.pnpm/next@13.1.1_hrdbe576m4w26u2yfpqpvbxyky/node_modules/next/dist/client/dev/amp-dev.js
Error: failed to process failed to invoke plugin: failed to invoke plugin on 'Some("/xxx/node_modules/.pnpm/next@13.1.1_hrdbe576m4w26u2yfpqpvbxyky/node_modules/next/dist/client/dev/amp-dev.js")'

Caused by:
    0: failed to invoke `xxx/node_modules/.pnpm/swc-plugin-coverage-instrument@0.0.18/node_modules/swc-plugin-coverage-instrument/target/wasm32-wasi/release/swc_plugin_coverage.wasm` as js transform plugin at xxx/node_modules/.pnpm/swc-plugin-coverage-instrument@0.0.18/node_modules/swc-plugin-coverage-instrument/target/wasm32-wasi/release/swc_plugin_coverage.wasm
    1: RuntimeError: call stack exhausted
    2: stk_ovf

**Comment by kwonoj** [comment]
It is not possible to investigate further without minimal reproduction, which should be a standalos code can repro without other framework i.e next.js.
