### ISSUE TITLE
CSP compatibility

### ISSUE THREAD

**Issue by himself65** [kwonoj/swc-plugin-coverage-instrument#221]
remove this grammar

```ts
new (function() {}).constructor("return this")()
```

![image](https://github.com/kwonoj/swc-plugin-coverage-instrument/assets/14026360/11dd17f3-437e-4fda-b2b1-2ba40fd7a6c2)

**Comment by himself65** [comment]
https://github.com/kwonoj/swc-plugin-coverage-instrument/blob/adbcef991dfc0b7a83a8c6663d61b58f7c5da630/packages/swc-coverage-instrument/src/coverage_template/create_global_stmt_template.rs#L12-L40

**Comment by himself65** [comment]
Related: https://github.com/istanbuljs/istanbuljs/issues/621

**Comment by kwonoj** [comment]
This lib intends to mimic output as close to the upstream istanbul. Once upstream have it I may mimic same.

**Comment by himself65** [comment]
Upstream already supported this

https://github.com/istanbuljs/istanbuljs/issues/621#issuecomment-1746309641

**Comment by umanghome** [comment]
@kwonoj Hi. Can this be reopened? The issue is already fixed in istanbuljs.

**Comment by travzhang** [comment]
What's the problem with this approach? When instrumented at compile time, it can be recognized as a true global object at different runtimes.
