### ISSUE TITLE
Incomplete instrumentation for nested functions

### ISSUE THREAD

**Issue by astik** [kwonoj/swc-plugin-coverage-instrument#224]
Hi,
First of all, thanks for your plugin, it help us greatly in our tooling process in order to pass our quality gate ❤️ 

We have found a very tricky issue when defining nested function / callback and chaining with boolean operator.

For example:
```
data?.map((stat) => {
  console.log(stat); <-- no instrumentation :'(
  return "bla"; <-- no instrumentation :'(
}) || [];

(data || []).map((stat) => {
  console.log(stat);  <-- instrumentation!
  return "bla"; <-- instrumentation!
});
```

Doing the instrumentation with NYC, i have no issue, everything is covered.

Repo for reproducing the issue on a minimal scope: https://github.com/astik/swc-plugin-coverage-instrument-issue-224.

**Comment by kwonoj** [comment]
Probably there's some uncovered paths in the visitor. I may not have time to look into this, but happy to accept a PR with corresponding test case.

**Comment by astik** [comment]
Would have love to help this project, but i've got no knowledge about Rust :'(

**Comment by kwonoj** [comment]
I think this is adquetely resolved with latest release.
