### ISSUE TITLE
EvalError on Next.js using middleware

### ISSUE THREAD

**Issue by TCezarRod** [kwonoj/swc-plugin-coverage-instrument#226]
If we use the plugin on a Next.js app with a middleware set up, the following error occurs in the production build:

```
/my-local-path/next-js-swc-plugin-coverage-instrument/.next/server/src/middleware.js:62
var global1 = new ((function(){}).constructor)("return this")();
^

EvalError: Code generation from strings disallowed for this context
at new Function (<anonymous>)
  at cov_11952777981831602621 (/my-local-path/next-js-swc-plugin-coverage-instrument/.next/server/src/middleware.js:62:19)
  at 884 (/my-local-path/next-js-swc-plugin-coverage-instrument/.next/server/src/middleware.js:881:1)
  at __webpack_require__ (/my-local-path/next-js-swc-plugin-coverage-instrument/.next/server/edge-runtime-webpack.js:25:42)
  at __webpack_exec__ (/my-local-path/next-js-swc-plugin-coverage-instrument/.next/server/src/middleware.js:58623:48)
  at /my-local-path/next-js-swc-plugin-coverage-instrument/.next/server/src/middleware.js:58624:37
  at webpackJsonpCallback (/my-local-path/next-js-swc-plugin-coverage-instrument/.next/server/edge-runtime-webpack.js:146:39)
  at /my-local-path/next-js-swc-plugin-coverage-instrument/.next/server/src/middleware.js:2:61
  at Script.runInContext (node:vm:134:12)
  at runInContext (node:vm:282:6)
```

This only happens when running the production build, i.e.:
```shell
next build
next start
```

Running the dev environment (with `next dev`) is OK.

The issue also doesn't happen if the app doesn't include a middleware file.

I've set up a minimal reproduction at
https://github.com/TCezarRod/next-js-swc-plugin-coverage-instrument

**Comment by TCezarRod** [comment]
I'm sorry, but after some investigation I noticed that this might be an issue with Next.js itself, not `swc-plugin-coverage-instrument`.

The Edge runtime on Next.js does not allow some native node functions for dynamic code evaluation (see [this error page](https://nextjs.org/docs/messages/edge-dynamic-code-evaluation)). The line that triggers the error is `new ((function(){}).constructor)("return this")()`, which is not supported in the edge runtime.

Apparently, you cannot disable the edge runtime for middlewares in Next.js yet, even though some parts of the documentation might mislead you to believe you can. There are some issues regarding the problem, for example: https://github.com/vercel/next.js/discussions/46722 

But we haven't got much response from the team. 

In regards of the plugin, I'm closing the issue as the solution will probably be elsewhere. Sorry for the confusion.

**Comment by lhimstedt** [comment]
@TCezarRod I struggled with the same problem and I thought using the new unstableExclude configuration option for this library would solve my problem. But somehow the file does not look different after excluding. The output is still creating the .eval error. As soon as I remove the plugin completely it works.

Have you tried the new exclude parameter?

**Comment by xiaowu2333** [comment]
@lhimstedt 
I've faced the same issue and tried using unstableExclude as well, but it didn’t work for me either. Removing the middleware file or disabling the plugin does resolve the issue. Have you managed to solve it?

**Comment by misaon** [comment]
After a long and deep debugging I managed to find a solution to solve all this. The problem is that `middleware.ts` and `instrumentation.ts` are the two elements that use the **runtime edge**.

If we want to instrument the code using **SWC**, we need to ensure that we **don't run it over these two files**. For these needs, we will need to configure the `unstableExclude` option that is part of this plugin.

So we will **exclude** `src/instrumentation.ts` and **any dependencies that are imported** into `middleware.ts`.

`next.config.mjs`
```ts
experimental: {
  swcPlugins: [
    [
      'swc-plugin-coverage-instrument',
      {
        unstableExclude: [
          // Files below are to be ignored if you use NextResponse.redirect(...) in middleware
          '**/node_modules/next/dist/esm/client/components/router-reducer/**/*',
          '**/node_modules/next/dist/esm/client/components/*.js',
          '**/node_modules/next/dist/esm/shared/lib/i18n/**/*',
          '**/node_modules/next/dist/esm/shared/lib/page-path/**/*',
          '**/node_modules/next/dist/esm/shared/lib/router/**/*',
          '**/node_modules/next/dist/esm/shared/lib/*.js',
          '**/src/instrumentation.ts',  // optional: only if you use instrumentation.ts (for Sentry etc.)
          // Add local files in imported into middleware.ts
          // e.g. '**/src/auth.config.ts'
        ],
      },
    ],
  ],
},
```

However, it is important to explicitly tell **Istanbul** not to resolve the middleware file, this is done by using the **annotation** right at the **beginning** of the `middleware.ts` file:

`src/middleware.ts`
```ts
/* istanbul ignore file */

// middlware ...
```

**Comment by stovmascript** [comment]
@misaon Can you elaborate how you went about debugging which files to exclude? We have a similar setup, using `NextResponse.rewrite` instead of `.redirect` in our `src/instrumentation.ts`.

We're also using Next.js' `output: 'standalone'` (to build a Docker image) and I'm trying to track down an issue where I'm able to build and run locally, but will run into this error during runtime from the Docker image.

**Comment by stovmascript** [comment]
@misaon Also, thank you for taking the time to dig into this and posting your well written solution 👌

**Comment by stovmascript** [comment]
> @misaon Can you elaborate how you went about debugging which files to exclude? We have a similar setup, using `NextResponse.rewrite` instead of `.redirect` in our `src/instrumentation.ts`.
> 
> We're also using Next.js' `output: 'standalone'` (to build a Docker image) and I'm trying to track down an issue where I'm able to build and run locally, but will run into this error during runtime from the Docker image.

Looks like I figured out a working combination.

`sentry.edge.config.ts`
```ts
/* istanbul ignore file */
import * as Sentry from '@sentry/nextjs'
```
