### ISSUE TITLE
Query : How to check if instrumentation is done or not in browser?

### ISSUE THREAD

**Issue by GeekyMoron** [kwonoj/swc-plugin-coverage-instrument#231]
I have a use case where we wanted to measure e2e coverage through istanbul, prior to this plugin we were using babel istanbul plugin for instrumentation and when application starts coverage info is present under, window.__coverage__ object, but after using  swc plugin coverage, we found that window.__coverage__ object is undefined , **so what is the process to check instrumentation with this?** plugin as we will be consuming that coverage info.
used this way under next.config.js:
  experimental: {
    swcPlugins:
      [
        "swc-plugin-coverage-instrument",
        {
          coverageVariable: "__coverage__",
          esModules: true,
          debug: true,
          instrumentLog: {
            level: "info"
          }
        }
      ]
  }
  version used: 0.0.13

**Comment by kwonoj** [comment]
unlike babel swc's plugin does not have access to external environment. Instead, there's some naive approach to attach coverage information to the transformed output itself as json-parseable comment to postprocess if needed. https://github.com/kwonoj/swc-plugin-coverage-instrument/blob/6438b88c2f58c072115d021c1b3c05f836bf4f83/spec/util/verifier.ts#L62-L90 shows some example.

I am not able to say if this can be used for the specific tool you're using for the e2e test though, that depends if tool allows to chain transform to other postprocess steps.
