### ISSUE TITLE
No coverage picked up by Cypress

### ISSUE THREAD

**Issue by mildfuzz** [kwonoj/swc-plugin-coverage-instrument#232]
using NextJS@latest, I have the following config:

```
swcPlugins: [
      [
        'swc-plugin-coverage-instrument',
        {esModules: true, reportLogic: true, produceSourceMap: true},
      ],
    ],
```

and using @cypress/code-coverage plugin, cypress reports no instrumentation. I think I am missing a step but I can't figure out what it might be. 

I tried adding `"instrumenter": "nyc",` to the nyc stanza in my `package.json`, but this leads to this issue: https://github.com/cypress-io/code-coverage/issues/804

**Comment by kwonoj** [comment]
https://github.com/kwonoj/swc-plugin-coverage-instrument/issues/163#issuecomment-1188379363

https://github.com/cypress-io/code-coverage/issues/583
