### ISSUE TITLE
Full coverage

### ISSUE THREAD

**Issue by sherlockfeng** [kwonoj/swc-plugin-coverage-instrument#240]
Hi, i find that this plugin only collect files that running in test.
`babel-plugin-istanbul` support onCover function to collect full coverage form all files in project.
Is there an chance this plugin also support similar abilities ?

**Comment by kwonoj** [comment]
Swc's plugin architecture currently does not have a way to accept callback from js.

**Comment by sherlockfeng** [comment]
Perhaps there is no need for a JS callback,  generate the instrumentation and coverage data in the specified folder is enough

**Comment by kwonoj** [comment]
That also doesn't work in swc's plugin as filesystem access is limited and there isn't global hook to consolidate some information.
