### ISSUE TITLE
Unstable Exclude config isn't excluding node_modules directory

### ISSUE THREAD

**Issue by bettblake08** [kwonoj/swc-plugin-coverage-instrument#244]
I'm currently running NextJs v14.2.5 with the latest swc instrumentation plugin and I'm encountering 2 issues (likely related).

1. I'm unable to exclude the node_modules directory from instrumentation which results in the coverage reports capturing code coverage in the node_modules files.
2. It also seems the plugin is affecting the swc build rules by including the node_modules directory in it's checks for the "use client" directive. I've been getting errors from the AntD UI library given that the "use client" directive is being declared after the "use strict". If I remove the plugin from the list of `swcPlugins` in the NextJs config, the builds are successful, so my assumption is that if the exclude config works as expected, the builds would run successfully.

![Screenshot 2024-08-20 at 20 03 45](https://github.com/user-attachments/assets/4e870cfa-93fb-4e6d-8365-fe68bc03d313)

Here's my swc config. As you can see, I don't think there's an issue with the glob pattern defined. Would you have an idea of what's wrong with this config?

```
const nextConfig = {
  output: 'standalone',
  experimental: {
    instrumentationHook: true, // OTEL instrumentation
    swcPlugins: [
      [
        'swc-plugin-coverage-instrument',
        {
          unstableExclude: ['node_modules/**/*'],
        },
      ],
    ],
  },

 ...
};
```

I'm using the following lib versions:

```
 "next": "^14.2.5",
 "swc-plugin-coverage-instrument": "^0.0.24"
```

**Comment by jyrkih** [comment]
I had the same issue, but this format seems to work
`unstableExclude: ['**/node_modules/**'],`

**Comment by bettblake08** [comment]
@jyrkih Thank you! The pattern works and resolves all the mentioned issues.

**Comment by jpierson-at-riis** [comment]
This solution still does not seem to work for me. Node modules are still instrumented apparently and included in the corresponding coverage report.

next: `14.2.13`
swc-plugin-coverage-instrument: `^0.0.24`

**Comment by lukpsaxo** [comment]
I also cannot get it to work. It was in a webpack config so I created one rule for things that should be instrumented and one for the one that shouldn't and then only added the plugin on one rule.

I tried

**/node_modules/**
**/node_modules/**/*.*
/**/node_modules/**/*.*

and many other possibilities.

Its on windows.
