### ISSUE TITLE
Server side code executed at build time and run time don't appear to collect coverage 

### ISSUE THREAD

**Issue by jpierson-at-riis** [kwonoj/swc-plugin-coverage-instrument#246]
When attempting to collect coverage information through CypressJS and NextJS configured with the `swc-plugin-coverage-instrument`, any source code which executes during the build process in the case of an exported web app (SSG) or when running the dev server (SSR) does not appear to show in the coverage results. CypressJS expects to find the coverage information in the `__coverage__` global variable but also appears to issue a request to get the resources at `/__coverage__` in order to combine server side and client side results. If a `__coverage__` file is generated as part of the exported build or served up dynamically from the dev server or server in the case of production SSR then coverage over server side code should be able to be collected and merged with the client side coverage for tools like CypressJS and others.

Reference: https://docs.cypress.io/guides/tooling/code-coverage#Full-stack-code-coverage

Package Version: `0.0.24`
Node Version: v20.16.0
NPM Version: 10.8.1
OS: Windows 10
Framework: NextJS

**Comment by kwonoj** [comment]
At the moment I would put this same bucket to https://github.com/kwonoj/swc-plugin-coverage-instrument/issues/163 . SWC's plugin have very limited filesystem access and it cannot mimic what istanbul does to conform external tool consume.

**Comment by jpierson-at-riis** [comment]
As an update it looks like maybe there is an alternative approach other than having the backend coverage be carried over to the frontend although that approach I believe should work in theory. Instead Cypress, and perhaps other tools, will attempt to request the coverage for any backend code through an API call. It appears that the coverage data is there in the backend so it just needs to be exposed through an API. In the case of NextJS this is pretty simple to do with a route handler as an example and other frameworks could likely do something similar. Please see the example below.

https://github.com/bahmutov/next-and-cypress-example?tab=readme-ov-file#coverage

Based on what I've learned so far, it seems like NextJS would benefit from having higher level option for for enabling coverage which would add this `swc-plugin-coverage-instrument` plugin automatically as well as to enable a built in coverage API endpoint for both the dev server and when exporting.
