### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by jesperume** [kwonoj/swc-plugin-coverage-instrument#250]
Thanks for a good plugin. When can we expect a new version to be released with the last changes in master? So that we would be able to upgrade to a newer SWC version. It's holding us back at the moment.

**Comment by jesperume** [comment]
@kwonoj Can you kindly look into releasing a new version?

**Comment by kwonoj** [comment]
Having a limited access at work, wasn't able to check things. https://github.com/kwonoj/swc-plugin-coverage-instrument/releases/tag/v0.0.25
